=== dekarl/atlas/src/test/resources/tv_channel_data.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT tv_channel_data (stations, regions?, service_providers?, platforms?)>

<!ELEMENT stations (station+)>

<!ELEMENT station (names, channels)>
<!ATTLIST station
  id CDATA #REQUIRED
>

<!ELEMENT channels (channel+)>

<!ELEMENT channel (names, variation*, logos?, provider_channel_ids?)>
<!ATTLIST channel
  id CDATA #REQUIRED
  start_date CDATA #REQUIRED
  format CDATA #IMPLIED
  media_type CDATA #IMPLIED
>


<!-- timeshift attribute indicates number of minutes channel is timeshifted from base channel and appears on timeshift type variation channels only -->
<!-- base_channel_id indicates the channel that this channel is a variation of and appears on timeshift and HD type variations only -->
<!-- type regional indicates that this channel is a regional variation. timeshift and base_channel_id attrubutes will not be present for regional type variations -->
<!ELEMENT variation EMPTY>
<!ATTLIST variation
  type CDATA #REQUIRED
  base_channel_id CDATA #IMPLIED
  timeshift CDATA #IMPLIED
>

<!ELEMENT logos (logo+)>
<!ELEMENT logo (#PCDATA)>
<!ATTLIST logo
  start_date CDATA #REQUIRED
  end_date CDATA #IMPLIED
  width CDATA #REQUIRED
  height CDATA #REQUIRED
>


<!ELEMENT provider_channel_ids (provider_channel_id+)>
<!ELEMENT provider_channel_id (#PCDATA)>
<!ATTLIST provider_channel_id
  service_provider_id CDATA #REQUIRED
>

<!-- Services e.g. Sky, Freeview -->
<!ELEMENT service_providers (service_provider+)>
<!ELEMENT service_provider (names, regionalisation_list?)>
<!ATTLIST service_provider
  id CDATA #REQUIRED
>

<!-- NOTE: region_id references region_id of region element -->
<!ELEMENT regionalisation_list (regionalisation+)>
<!ELEMENT regionalisation EMPTY>
<!ATTLIST regionalisation
  region_id CDATA #REQUIRED  
>

<!-- Platforms e.g. Sky HD, Freeview -->
<!ELEMENT platforms (platform+)>
<!ELEMENT platform (names, countries?, epg)>
<!ATTLIST platform
  id CDATA #REQUIRED
  service_provider_id CDATA #REQUIRED
>

<!ELEMENT countries (country+)>
<!ELEMENT country (#PCDATA)>
<!ATTLIST country
  code CDATA #REQUIRED
>

<!-- Regions -->
<!ELEMENT regions (region+)>
<!ELEMENT region (names)>
<!ATTLIST region
  id CDATA #REQUIRED
>


<!-- name which can be date dependent due to entity changing its name from a particular date -->
<!ELEMENT names (name+)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name 	start_date	CDATA	#REQUIRED>
<!ATTLIST name 	end_date	CDATA	#IMPLIED>
<!ATTLIST name 	type CDATA	#IMPLIED>


<!-- platform_epg_content -->
<!ELEMENT epg (epg_content+)>

<!ELEMENT epg_content (regionalisation_list?)>
<!ATTLIST epg_content
  channel_number CDATA #REQUIRED
  channel_id CDATA #REQUIRED
  start_date CDATA #REQUIRED
  end_date CDATA #IMPLIED
>

=== dekarl/atlas/src/test/resources/201212141542_tv_channel_data.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE tv_channel_data SYSTEM "tv_channel_data.dtd">

<tv_channel_data>
  <stations>
    <station id="1">
      <names>
        <name start_date="2012-11-13">BBC One</name>
      </names>
      <channels>
        <channel id="11" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One West Midlands</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131474.png</logo>
          </logos>
        </channel>
        <channel id="1663" start_date="2011-11-22" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Channel Islands</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131731.png</logo>
          </logos>
        </channel>
        <channel id="17" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One South West</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131742.png</logo>
          </logos>
        </channel>
        <channel id="2" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Scotland</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131774.png</logo>
          </logos>
        </channel>
        <channel id="1" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Northern Ireland</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131751.png</logo>
          </logos>
        </channel>
        <channel id="18" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One West</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131747.png</logo>
          </logos>
        </channel>
        <channel id="16" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One South East</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131738.png</logo>
          </logos>
        </channel>
        <channel id="13" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One North East &amp; Cumbria</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131544.png</logo>
          </logos>
        </channel>
        <channel id="1665" start_date="2011-11-22" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Yorkshire &amp; Lincolnshire</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131733.png</logo>
          </logos>
        </channel>
        <channel id="713" start_date="2001-09-05" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One London</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131847.png</logo>
          </logos>
        </channel>
        <channel id="3" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Wales</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131785.png</logo>
          </logos>
        </channel>
        <channel id="9" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One East</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131916.png</logo>
          </logos>
        </channel>
        <channel id="12" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Yorkshire</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131512.png</logo>
          </logos>
        </channel>
        <channel id="14" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One North West</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131610.png</logo>
          </logos>
        </channel>
        <channel id="15" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One South</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131677.png</logo>
          </logos>
        </channel>
        <channel id="1664" start_date="2011-11-22" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Cambridgeshire</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131732.png</logo>
          </logos>
        </channel>
        <channel id="1662" start_date="2011-11-22" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One Oxfordshire</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131730.png</logo>
          </logos>
        </channel>
        <channel id="10" start_date="1999-01-01" media_type="TV">
          <names>
            <name start_date="2012-11-13">BBC One East Midlands</name>
          </names>
          <variation type="regional" />
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131467.png</logo>
          </logos>
        </channel>
      </channels>
    </station>
    <station id="518">
      <names>
        <name start_date="2012-11-28">BBC Four</name>
      </names>
      <channels>
        <channel id="742" start_date="2002-02-14" media_type="TV">
          <names>
            <name start_date="2012-11-28">BBC Four</name>
          </names>
          <logos>
            <logo width="320" start_date="2012-11-21" height="180">p131854.png</logo>
          </logos>
        </channel>
      </channels>
    </station>
  </stations>
  <regions>
    <region id="47">
      <names>
        <name start_date="2000-01-01">Cambridgeshire</name>
      </names>
    </region>
    <region id="48">
      <names>
        <name start_date="2000-01-01">Channel Islands</name>
      </names>
    </region>
    <region id="49">
      <names>
        <name start_date="2000-01-01">Cumbria</name>
      </names>
    </region>
    <region id="50">
      <names>
        <name start_date="2000-01-01">East</name>
      </names>
    </region>
    <region id="51">
      <names>
        <name start_date="2000-01-01">East Midlands</name>
      </names>
    </region>
    <region id="52">
      <names>
        <name start_date="2000-01-01">Yorkshire &amp; Lincolnshire</name>
      </names>
    </region>
    <region id="53">
      <names>
        <name start_date="2000-01-01">London</name>
      </names>
    </region>
    <region id="54">
      <names>
        <name start_date="2000-01-01">North East</name>
      </names>
    </region>
    <region id="55">
      <names>
        <name start_date="2000-01-01">North West</name>
      </names>
    </region>
    <region id="56">
      <names>
        <name start_date="2000-01-01">Northern Ireland</name>
      </names>
    </region>
    <region id="57">
      <names>
        <name start_date="2000-01-01">Oxfordshire</name>
      </names>
    </region>
    <region id="58">
      <names>
        <name start_date="2000-01-01">Scotland (Borders)</name>
      </names>
    </region>
    <region id="59">
      <names>
        <name start_date="2000-01-01">Scotland (Central)</name>
      </names>
    </region>
    <region id="60">
      <names>
        <name start_date="2000-01-01">Scotland (North)</name>
      </names>
    </region>
    <region id="61">
      <names>
        <name start_date="2000-01-01">South</name>
      </names>
    </region>
    <region id="62">
      <names>
        <name start_date="2000-01-01">South East</name>
      </names>
    </region>
    <region id="63">
      <names>
        <name start_date="2000-01-01">South West</name>
      </names>
    </region>
    <region id="64">
      <names>
        <name start_date="2000-01-01">Wales</name>
      </names>
    </region>
    <region id="65">
      <names>
        <name start_date="2000-01-01">West</name>
      </names>
    </region>
    <region id="66">
      <names>
        <name start_date="2000-01-01">West Midlands</name>
      </names>
    </region>
    <region id="67">
      <names>
        <name start_date="2000-01-01">Yorkshire</name>
      </names>
    </region>
  </regions>
  <service_providers>
    <service_provider id="2">
      <names>
        <name start_date="2000-01-01">Freeview</name>
      </names>
    </service_provider>
    <service_provider id="9">
      <names>
        <name start_date="2000-01-01">YouView</name>
      </names>
